# Task 2.2: Project Planning and Sourcing Data with an API
#### 1. Install libraries
#### 2. Read in data and join it
#### 3. Get weather data using NOAA's API
#### 4. Merge the weather data with New York CitiBike data set and export it to a CSV file

### 1. Install libraries

In [1]:
# Installing libraries
import pandas as pd 
import numpy as np
import os 
import requests
import json
from datetime import datetime

### 2. Read in data and join it

In [2]:
# Create a list with all files in the folder using a list comprehension
folderpath = r"Data" 
filepath = [os.path.join(folderpath, name) for name in os.listdir(folderpath) if name.endswith(".csv")]
filepath

['Data/202208-citibike-tripdata_3.csv',
 'Data/202207-citibike-tripdata_2.csv',
 'Data/202207-citibike-tripdata_3.csv',
 'Data/202208-citibike-tripdata_2.csv',
 'Data/202207-citibike-tripdata_1.csv',
 'Data/202208-citibike-tripdata_1.csv',
 'Data/202210-citibike-tripdata_1.csv',
 'Data/202207-citibike-tripdata_4.csv',
 'Data/202208-citibike-tripdata_4.csv',
 'Data/202203-citibike-tripdata_2.csv',
 'Data/202210-citibike-tripdata_2.csv',
 'Data/202203-citibike-tripdata_1.csv',
 'Data/202210-citibike-tripdata_3.csv',
 'Data/202204-citibike-tripdata_1.csv',
 'Data/202204-citibike-tripdata_2.csv',
 'Data/202204-citibike-tripdata_3.csv',
 'Data/202211-citibike-tripdata_3.csv',
 'Data/202202-citibike-tripdata_1.csv',
 'Data/202211-citibike-tripdata_2.csv',
 'Data/202202-citibike-tripdata_2.csv',
 'Data/202209-citibike-tripdata_4.csv',
 'Data/202206-citibike-tripdata_4.csv',
 'Data/202211-citibike-tripdata_1.csv',
 'Data/202209-citibike-tripdata_1.csv',
 'Data/202206-citibike-tripdata_1.csv',
 'Data/202206-citibike-tripdata_3.csv',
 'Data/202209-citibike-tripdata_2.csv',
 'Data/202209-citibike-tripdata_3.csv',
 'Data/202206-citibike-tripdata_2.csv',
 'Data/202205-citibike-tripdata_3.csv',
 'Data/202205-citibike-tripdata_2.csv',
 'Data/202205-citibike-tripdata_1.csv',
 'Data/202201-citibike-tripdata_2.csv',
 'Data/202212-citibike-tripdata_1.csv',
 'Data/202201-citibike-tripdata_1.csv',
 'Data/202212-citibike-tripdata_2.csv']

In [3]:
# Read in data and concatenate all files simultaneously
df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)

/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)
/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/3746176992.py:2: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in filepath), ignore_index = True)

In [4]:
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9D0DC440CB40CF8E,electric_bike,2022-08-27 13:56:47.728,2022-08-27 14:02:56.651,Flatbush Ave & Ocean Ave,3704.04,3 St & Prospect Park West,3865.05,40.663657,-73.963014,40.668132,-73.973638,casual
1,2214991DFBE5C4D7,electric_bike,2022-08-20 10:37:02.756,2022-08-20 10:45:56.631,Forsyth St\t& Grand St,5382.07,E 11 St & 1 Ave,5746.14,40.717798,-73.993161,40.729538,-73.984267,casual
2,20C5D469563B6337,classic_bike,2022-08-31 18:55:03.051,2022-08-31 19:03:37.344,Perry St & Bleecker St,5922.07,Grand St & Greene St,5500.02,40.735354,-74.004831,40.721700,-74.002381,member
3,3E8791885BC189D1,classic_bike,2022-08-02 08:05:00.250,2022-08-02 08:16:52.063,FDR Drive & E 35 St,6230.04,Grand Army Plaza & Central Park S,6839.10,40.744219,-73.971212,40.764397,-73.973715,member
4,8DBCBF98885106CB,electric_bike,2022-08-25 15:44:48.386,2022-08-25 15:55:39.691,E 40 St & 5 Ave,6474.11,Ave A & E 14 St,5779.11,40.752052,-73.982115,40.730311,-73.980472,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29838801,1F223EDAFF420AE3,electric_bike,2022-12-01 20:26:45.847,2022-12-01 20:30:46.012,Avenue D & E 3 St,5436.09,Stanton St & Chrystie St,5523.02,40.720701,-73.977939,40.722293,-73.991475,member
29838802,CFA5C560ACB73B8E,classic_bike,2022-12-26 13:46:34.237,2022-12-26 13:52:43.900,43 Ave & 47 St,6209.05,39 Ave & 45 St,6401.03,40.744806,-73.917290,40.749478,-73.918265,member
29838803,11C8C5E0DB947B07,classic_bike,2022-12-01 05:56:14.903,2022-12-01 06:06:10.357,Avenue D & E 3 St,5436.09,Bleecker St & Crosby St,5679.08,40.720828,-73.977932,40.726156,-73.995102,member
29838804,5B9B083C534A5964,classic_bike,2022-12-02 11:54:15.871,2022-12-02 12:01:00.747,Montague St & Clinton St,4677.06,Sands St & Jay St,4821.03,40.694271,-73.992327,40.700119,-73.986200,member
29838805,91C286C462F89A50,classic_bike,2022-12-18 13:35:22.574,2022-12-18 13:37:27.193,Montague St & Clinton St,4677.06,Cadman Plaza E & Tillary St,4677.01,40.694271,-73.992327,40.695977,-73.990149,member

####  Q5 Comment: The data folder has been created within the working directory, containing only the stored data files. Its path is saved in the string variable 'folderpath' and checks if each file ends with .csv to include only CSV files. The join function joins 'Folderpath' and 'Name' to get the full file path for each CSV file.  The result is a list called 'Filepath', containing the paths of all CSV files in the 'Data' folder.  The next step creates a generator that reads each file in filepath and produces a dataframe for each CSV file.  The concat function concatenates these dataframes into a single dataframe, combining all rows from all CSV files.

### 3. Get weather data using NOAA's API

In [5]:
# Defining token
token = 'XiCjTQWbEHpVzRSYNbfzbAriDgFyzVjH'

In [6]:
# Get the API
r = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=TAVG&limit=1000&stationid=GHCND:USW00014732&startdate=2022-01-01&enddate=2022-12-31', headers={'token':token})

In [7]:
# Load the API response as a json
d = json.loads(r.text)

In [8]:
# Secure all items in the response that correspond to TAVG
avg_temps = [item for item in d['results'] if item['datatype']=='TAVG']

In [9]:
# Get only the date field from all average temperature readings
dates_temp = [item['date'] for item in avg_temps]

In [10]:
# Get the temperature from all average temperature readings
temps = [item['value'] for item in avg_temps]

In [11]:
# Put the results in a dataframe
df_temp = pd.DataFrame()

In [12]:
# Get only date and cast it to date time; convert temperature from tenths of Celsius to Fahrenheit
df_temp['date'] = [datetime.strptime(d, "%Y-%m-%dT%H:%M:%S") for d in dates_temp]
df_temp['avgTemp'] = [(float(v)/10.0) * 9/5 + 32 for v in temps]

In [13]:
df_temp

          date  avgTemp
0   2022-01-01    52.88
1   2022-01-02    52.52
2   2022-01-03    34.52
3   2022-01-04    27.14
4   2022-01-05    37.76
..         ...      ...
360 2022-12-27    30.74
361 2022-12-28    38.12
362 2022-12-29    43.52
363 2022-12-30    48.74
364 2022-12-31    46.76

[365 rows x 2 columns]

In [14]:
df.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [15]:
df['started_at'] = pd.to_datetime(df['started_at'], dayfirst = True)

/var/folders/qg/tbv61t9j3ngdmw6m2qtbk34w0000gn/T/ipykernel_73572/1953011556.py:1: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S.%f format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['started_at'] = pd.to_datetime(df['started_at'], dayfirst = True)

In [16]:
df['date'] = pd.to_datetime(df['started_at'], format='%Y-%m-%d').dt.date

In [17]:
df['date'] = pd.to_datetime(df['date'])

In [18]:
df_temp.head()

        date  avgTemp
0 2022-01-01    52.88
1 2022-01-02    52.52
2 2022-01-03    34.52
3 2022-01-04    27.14
4 2022-01-05    37.76

### 4. Merge the weather data with New York CitiBike data set and export it to a CSV file

In [19]:
%%time
df_merged = df.merge(df_temp, how = 'left', on = 'date', indicator = True)

CPU times: user 5.84 s, sys: 28.1 s, total: 33.9 s
Wall time: 3min 37s

In [20]:
df_merged.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,avgTemp,_merge
0,9D0DC440CB40CF8E,electric_bike,2022-08-27 13:56:47.728,2022-08-27 14:02:56.651,Flatbush Ave & Ocean Ave,3704.04,3 St & Prospect Park West,3865.05,40.663657,-73.963014,40.668132,-73.973638,casual,2022-08-27,82.04,both
1,2214991DFBE5C4D7,electric_bike,2022-08-20 10:37:02.756,2022-08-20 10:45:56.631,Forsyth St\t& Grand St,5382.07,E 11 St & 1 Ave,5746.14,40.717798,-73.993161,40.729538,-73.984267,casual,2022-08-20,82.22,both
2,20C5D469563B6337,classic_bike,2022-08-31 18:55:03.051,2022-08-31 19:03:37.344,Perry St & Bleecker St,5922.07,Grand St & Greene St,5500.02,40.735354,-74.004831,40.721700,-74.002381,member,2022-08-31,78.08,both
3,3E8791885BC189D1,classic_bike,2022-08-02 08:05:00.250,2022-08-02 08:16:52.063,FDR Drive & E 35 St,6230.04,Grand Army Plaza & Central Park S,6839.10,40.744219,-73.971212,40.764397,-73.973715,member,2022-08-02,79.52,both
4,8DBCBF98885106CB,electric_bike,2022-08-25 15:44:48.386,2022-08-25 15:55:39.691,E 40 St & 5 Ave,6474.11,Ave A & E 14 St,5779.11,40.752052,-73.982115,40.730311,-73.980472,member,2022-08-25,82.58,both

In [21]:
df_merged['_merge'].value_counts(dropna = False)

_merge
both          29838166
left_only          640
right_only           0
Name: count, dtype: int64

In [22]:
df_merged.to_csv('LaGuardia_data.csv')

In [23]:
df.shape

(29838806, 14)